version: '3.8'

services:
  app:
    container_name: app-dev
    image: development
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 2003:2003